"""集中定义主界面卡片、布局和事件批处理常量。"""

CARD_HEIGHT = 108
CARD_COLUMNS = 2
CARD_COLUMN_SPACING = 10
UI_EVENT_BATCH_LIMIT = 80
# 主窗口只消费队列和刷新 UI，缩短轮询可减少跨进程事件到达后的体感等待。
UI_EVENT_POLL_INTERVAL_MS = 50
MONITOR_RECORDS_COALESCE_MS = 16
STARTUP_SERVICES_DELAY_MS = 50
